language: java
before_deploy:
- mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
- export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')
deploy:
  provider: releases
  api_key:
    secure: d4x+TYcbmF9haWZdRAbCWgBzNRcPi9Yb7Dleia7uCvTg6dOjm8wf26IrRRu09CkerKoBUy569bDmA2Ao9jFnHBzSDYxZQ1LCSl2dL/ZLJini2ghI6dYeUh1pj9CZav76pcHWr9lVLuryFQj27lOZBerrTWFM6+85bIXVUBgBpIsn2LHOOQSCThxQWuUCvFwysZY2yAmT54hCzRWjPaG9BDtBdPz9EazY146zQY3X9d8Z8fqhVCa4bSotg+8DccZx42kOM3UH/zdwuqppzQ3L3NeYHh2N836B8PItg/XOVwk4pxPgE8o0dIEqkLCE9e1ipaErbiQ9Fmwn/sDkzC19lsAmKCFcqM2rGxd64b/IxegdXtJzp+jUCN14weTQhrnabU7jD96fTMJ1MG3AdHGYCqCGlOxskFm7sH9lltmlXZh7jRHZytiPtYTTE4hgVrEmJy0wejzX3wnDjwATFOqj19650Ggx2WQQsWq//HsdplWXKfaVNDSD+hBU8LVOWC6eeNZ7CavuhXtflRooUWwfrMBFTyUSZtXUT2p63C2wQTFlVL3dJZ5pP6qsp30T1Mm3RvOt04gVSMEUM9DEj3WdpoSxvA4KKHl86FG1I6SNEpPsKOvQjoLj+SI7NMZ9TMLerxTlK337NiWeqXKOWZjxA9hyH/crRJnHmHNgi8Pwkcs=
  file:
    - pirg/target/prig-$project_version.jar
  skip_cleanup: true
  on:
    repo: werhardt/pirg
  name: $project_version