language: java
before_deploy:
- mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
- export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')
deploy:
  provider: releases
  api_key:
    secure: 3f6fb126bad5ed50f11e8254a2a0e3e2d8e52525
  file: pirg/target/pirg-$project_version.jar
  skip_cleanup: true
  on:
    repo: werhardt/pirg
  name: "$project_version"