language: java
before_deploy:
- mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
- export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep
  -v '\[')
deploy:
  provider: releases
  api-key:
    secure: cmIiJdSDwPVWtCCLxOu0ZwtQSow5HMZ3s8wZ3Nj2e31Rytg5lU+tj/bRwM0PqEB1LNOMRLIK2NR284JSBK59z1x2QoEvj/EJANTGN80fnR1X8mBOjGG1wifTX0ogWRZ8OR0JRCChHAA8i5wFZ89HHY752bV5sYKiIy18zn3DpWRemN/7b9QcJktiSKJYbUZYGOyLz42cIcEmlE+3UsxRzxoSqI+cYv2Rwg29WLNCfwdyRkqNbLSzrnj/k5RIu7e2zrDDH5kkSrBSz/X6LUqgEJC/fMJm8NOVdu8ggB0DP3ye4yTiARVoByi8BMiQkgR8J/s4QslAYzFCzvlNM6cZARNql3bKXtWSgSHeClYTD6F/8frKwPbcKFL1OwhuTWEwX8FQUrhYnW6huUTumJML7OlB4pLMoarGAkmM63G3dIxo26xx7SBQ+IJubCIsH3SQ1VbJYldiliRywuWz6Lz/dIQjBeJ+FanXsl4P/UjcQaIRZJbVjLGrA1xSgb8CNPT647Vp4N6s+jIBLv+11tkwLaeGdXzmbZ2IVp9dch2Ci9rOC1GsDlJG3Qnqkd2/cRA1ilMVJOuTAFB+HIKO3xoQaceA28ULjBmt7Bgblh9n0+tTo+oNHHEFLgwpNLoNNT7Keo69j1Ly7pvkCrxMoItbrbsU67iuGM6rjl0OSisKXbk=
  file: pirg/target/pirg-$project_version.jar
  skip_cleanup: true
  on:
    repo: werhardt/pirg
  name: "$project_version"
